### ISSUE TITLE
filter_func in SQuAD.py

### ISSUE THREAD

**Issue by zhangchen010295** [BangLiu/QANet-PyTorch#5]
In the line 308 you said that "# !!! use last answer as the target answer", and "start, end = example["y1s"][-1], example["y2s"][-1]"

However, in the function of def filter_func(config, example) in line 40, the 3rd condition is "(example["y2s"][0] - example["y1s"][0]) > config.ans_limit", which means the first answer is considered as the target answer (the index is 0, not -1)?

**Comment by zhangchen010295** [comment]
Besides, the condition should be "(example["y2s"][0] - example["y1s"][0]) >= config.ans_limit" ,not ">", because the answer span is a closed interval. For example, the answer "Professor of Chemistry and Physics", then y1=15 and y2=19, so the lenght should be 19-15 + 1=5

**Comment by zhangchen010295** [comment]
@BangLiu Could you please answer me? Thank you!

**Comment by BangLiu** [comment]
@zhangchen010295 Thanks for your suggestion! Yeah, I think your are right.
